debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.example.projectboardadmin: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: TRACE # 하이버네이트 6.0 부터 다음과 같이 문법 변경됨
    org.springframework.web.client.RestTemplate: debug

server.port: 8081

spring:
  devtools.livereload.port: 35730
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: eunchan
    password: 1234
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  h2.console.enabled: false
  sql.init.mode: always

  thymeleaf:
    cache: false
  thymeleaf3:
    decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

project.board.url: http://localhost:8080
---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always




